services:
  gui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gui
    ports:
      - "8501:8501"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=options_db
    volumes:
      - ../src:/app/src
    develop:
      watch:
        - path: ../src
          target: /app/src
          action: sync

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: options_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: