services:
  gui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gui
    ports:
      - "8501:8501"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-options_db}
    volumes:
      - ../src:/app/src
    develop:
      watch:
        - path: ../src
          target: /app/src
          action: sync

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-options_db}
      MYSQL_USER: ${MYSQL_USER:-options_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: