FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

ENV PYTHONPATH=/app

EXPOSE 8501

# Create a non-root user and switch to it
RUN useradd -m appuser
USER appuser

CMD ["streamlit", "run", "src/gui/streamlit_app.py"]