FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "src/gui/streamlit_app.py"]